const LITESEED_CONTRACT_PROCESS_ID = "rWBg5p-LGgbbUL8iMi2AmSqRi8aTFU4JChvHF35dPo4";
const MODULE = "XnL5if1y61soZRpsVJsOJ3-_8MinPtrhgH6dSOCxfoY";
const SCHEDULER = "TZ7o7SIZ06ZEJ14lXwVtng1EtSx60QkPy-kh-kdAXog";

export { MODULE, LITESEED_CONTRACT_PROCESS_ID, SCHEDULER };
